version: "3"

services:
  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - base_network
  web:
    container_name: fastapi
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: bash -c "alembic upgrade head && python3 ./run.py"
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - base_network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - base_network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  base_network:
    driver: bridge
