version: "3"

services:
  db:
    image: postgres:15
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  web:
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5050:5050"

volumes:
  app-db-data:
